### ISSUE TITLE
Return the name of the realm along with the public keys 

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-auth#104]
For now, the auth service returns one or more public keys to the WIT with only 2 data for each: the key id and the content of the public key. However, on the client (WIT) side, there's no easy way to identify the public keys. In my case, I need to configure the auth middleware of gin-gonic with a single public key and there's no direct way to tell which one to use. In devmode, the problem remains the same, since the `TokenManager` retrieves 3 public keys.

Ideally, could we add the name of the `realm` associated with the public keys ? Then on the WIT's `TokenManager`, we could add a method to look-up the public key per realm (including support for devmode)

**Comment by alexeykazakov** [comment]
Keycloak should be just an implementation detail. WIT should not have to know anything about Keycloak. We are not there yet but we are moving to that direction. WIT should talk to Auth with authentication and authorization requests instead of KC.
And now WIT should work with multiple keys anyway. Not all of them come from Keycloak. There is special key which is used to sign service account tokens. But all these keys are exposed by https://auth.openshift.io/api/token/keys
On top of that we should support multiple keys to rotate keys.

How you can determine which key to use? There is a Key ID Header in every token:
``"kid":"<KeyID>"` `
Check it to decide what key to use.
Here is an example in token manager how we do it when parsing token claims:

https://github.com/fabric8-services/fabric8-wit/blob/master/token/token.go#L134

**Comment by xcoulon** [comment]
yes, I've seen this `ParseToken` method but I can't use it the token parsing is taken care of by gin-gonic's JWT auth middleware. And this later must to be configured with a single public key, so I need to find which one to pass during the init. Yes, I could have an env variable that contains the ID of the key, but that seems wrong: if the key is revoked and replaced, then we'll need to update the WIT configuration. So, maybe giving info about the `realm` is wrong. What about returning a `usage` field to indicate if the key should be used to verify user's access tokens vs the `account service`'s tokens, then ?

**Comment by alexeykazakov** [comment]
The service account keys are places in the end of the key slice but how it will help you? You will have to validate service account tokens too. So, you need to support multiple keys right now. And later you will also need to support multiple keys for key rotation.
Proper key rotation is not when we just kill one key and replace it by a new one. We add a new key which is used to sign new tokens but keep the old one so too so the old tokens are valid. Then when all the tokens are refreshed we can remove the old key. So, users don't notice anything.

**Comment by xcoulon** [comment]
I thought that the service account would use different endpoints, which could be configured with a separate auth middleware. But indeed, the key rotation is another requirement, so I guess that the solution is rather to patch the gin-gonic JWT extension to support multiple public keys ! 
That being said, I can close this issue ;) 
Thanks for the clarification, @alexeykazakov !
