### ISSUE TITLE
update README with setup steps

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#107]
While setting up the codebase locally for development, please document the workarounds needed.

Assigned to @kishansag

**Comment by kishansag** [comment]
regarding this, the trouble I had were mostly because of different programs (like minishift) were messing up with each other. It is unlikely that someone else would face this problem. Even the solution that I used is not very graceful (reinstalling docker)
So I think instead of making changes in readme, it would make more sense if I just reference a previous pull request (https://github.com/fabric8-services/fabric8-auth/pull/101) to it

**Comment by alexeykazakov** [comment]
Our readme needs refactoring though.
It misses some important info like dependency on WIT.
