### ISSUE TITLE
In WIT use proxy instead of 307 redirects when the request should be handled by auth

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#135]
As part of the wit -> auth migration we added 307 redirects to WIT endpoints. So, WIT endpoints such as /users, /collaborators, etc redirects to auth. But it can cause problems in some cases if the client doesn't follow the redirect for some reason.
We need to proxy such requests instead of returning 307.

**Comment by alexeykazakov** [comment]
For example, this problem may affect this issue - https://github.com/openshiftio/openshift.io/issues/1053

**Comment by alexeykazakov** [comment]
I tried a very simple proxy like that:
```
func (c *UserController) Show(ctx *app.ShowUserContext) error {
    authUrl, err := url.Parse(c.config.GetAuthServiceURL())
    if err != nil {
        return jsonapi.JSONErrorResponse(ctx, err)
    }
    proxy := httputil.NewSingleHostReverseProxy(authUrl)
    proxy.ServeHTTP(ctx.ResponseData, ctx.Request)
    return nil
}
```
But ctx.Response is missing the response from the proxy for some reason. Needs some investigation.

**Comment by sbose78** [comment]
Hi @kishansagathiya 
Here's the commit where we added redirects from WIT to AUTH.

Example for listing collaborators, this was done: 
https://github.com/fabric8-services/fabric8-wit/pull/1667/files#diff-1aa086d3c540626ac82375f86f57c957L49

For the show user action this was done,
https://github.com/fabric8-services/fabric8-wit/pull/1667/files#diff-bd54c6f8d752494a3cf1a3eaaa074860R42

Now, instead of 307s ( redirects ) we need to delegate the request to the Auth service, ie, proxy the request. That involves creating a new HTTP from WIT to AUTH.

Could you please investigate the use of a `proxy`ing function to pass on the request from WIT to AUTH and then capture the response in WIT, which would eventually be returned as part of the response to the original request recieved by WIT ?

**Comment by alexeykazakov** [comment]
Please note that the idea is to use some pure reverse proxy (see an example above) instead of using goa clients as we did in that PR - https://github.com/fabric8-services/fabric8-wit/pull/1670
We need some proxy which will just copy all the original Headers, params and payload and call Auth service. Then copy all Headers and response body from Auth response and send it back to the original client.
