### ISSUE TITLE
Switch UI to new API to link accounts

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#157]
- [x] Switch UI to new API to link accounts 
- [x] Update GitHub oauth2 apps

Part of https://github.com/fabric8-services/fabric8-auth/issues/21

**Comment by rhopp** [comment]
Hi. What's the status of this issue? I have approved testing account (my second one) into osio, but I still cannot use it, because I didn't link it with github account. I'm waiting for this issue to be solved to be able to link that account to my existing github account (I already have one osio account linked to my gh account).
Or is there any other way how to link two accounts to one github account?

**Comment by alexeykazakov** [comment]
Still working on https://github.com/fabric8-ui/fabric8-ui/pull/2193 to make it happen.
You could use our API directly to connect your test account to the same GH. It can be tricky though.
You will need to run some app like this https://github.com/alexeykazakov/linker to do so. That app uses a local Auth though.

**Comment by alexeykazakov** [comment]
Done.
